"""Build: a visual spec becomes a valid NOOA Agent module."""

from __future__ import annotations

import ast
import textwrap
from pathlib import Path

from src.schemas import BuildSpec, FieldSpec, MethodSpec

STRATEGY_IMPORT = {
    "Predict": "PredictStrategy",
    "CodeAct": "CodeActStrategy",
}

_DEFAULTS = {"str": '""', "int": "0", "float": "0.0", "bool": "False"}
_MAX_BODY_LINES = 24
_FORBIDDEN = (
    "exec(",
    "eval(",
    "compile(",
    "__import__",
    "subprocess",
    "os.system",
    "os.popen",
    "pathlib.Path.home",
)


def generate_source(spec: BuildSpec) -> str:
    if not spec.methods:
        raise ValueError("add at least one method")
    agentic = [m for m in spec.methods if m.kind == "agentic"]
    strategies = sorted({STRATEGY_IMPORT[m.strategy] for m in agentic})
    role = _triple(spec.role.strip() or "You are a focused specialist agent.")
    chunks = [
        '"""Generated by ClassAct. Agent class for NVIDIA Object-Oriented Agents."""',
        "",
        "from nooa import Agent, strategy" if strategies else "from nooa import Agent",
    ]
    if strategies:
        chunks.append(f"from nooa.strategies import {', '.join(strategies)}")
    chunks += ["", "", f"class {spec.class_name}(Agent):", f'    """{role}"""', ""]
    if spec.fields:
        for field in spec.fields:
            chunks.append(_field_line(field))
        chunks.append("")
    for method in spec.methods:
        chunks.append(_method_block(method))
        chunks.append("")
    source = "\n".join(chunks).rstrip() + "\n"
    ast.parse(source)
    return source


def write_agent(spec: BuildSpec, workspace: Path) -> Path:
    source = generate_source(spec)
    workspace.mkdir(parents=True, exist_ok=True)
    path = workspace / f"{_mod_name(spec.class_name)}.py"
    path.write_text(source, encoding="utf-8")
    return path


def _mod_name(class_name: str) -> str:
    chars = []
    for i, ch in enumerate(class_name):
        if ch.isupper() and i and class_name[i - 1].islower():
            chars.append("_")
        chars.append(ch.lower())
    name = "".join(chars)
    if not name.endswith("_agent"):
        name = name + "_agent" if not name.endswith("agent") else name
    return name


def _field_line(field: FieldSpec) -> str:
    return f"    {field.name}: {field.type} = {_DEFAULTS[field.type]}"


def _method_block(method: MethodSpec) -> str:
    args = ", ".join(["self"] + [f"{a.name}: {a.type}" for a in method.args])
    doc = _triple(method.doc.strip() or f"Run {method.name}.")
    if method.kind == "python":
        body = _python_body(method)
        return (
            f"    def {method.name}({args}) -> {method.returns}:\n"
            f'        """{doc}"""\n'
            f"{body}"
        )
    strat = STRATEGY_IMPORT[method.strategy]
    return (
        f"    @strategy({strat}())\n"
        f"    async def {method.name}({args}) -> {method.returns}:\n"
        f'        """{doc}"""\n'
        f"        ..."
    )


def _python_body(method: MethodSpec) -> str:
    cleaned = _validate_python_body(method.body or "")
    if not cleaned:
        cleaned = f"return {_DEFAULTS.get(method.returns, 'None')}"
    return textwrap.indent(cleaned, "        ")


def _validate_python_body(body: str) -> str:
    cleaned = textwrap.dedent(body.replace("\t", "    ")).strip("\n")
    if not cleaned.strip():
        return ""
    lines = cleaned.splitlines()
    if len(lines) > _MAX_BODY_LINES:
        raise ValueError(f"Python tool body is limited to {_MAX_BODY_LINES} lines")
    lowered = cleaned.lower()
    for token in _FORBIDDEN:
        if token.lower() in lowered:
            raise ValueError(f"Python tool body cannot include {token}")
    try:
        ast.parse("def _tool():\n" + textwrap.indent(cleaned, "    "))
    except SyntaxError as exc:
        raise ValueError(f"invalid Python tool body: {exc.msg}") from exc
    return cleaned.strip("\n")


def _triple(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"""', "'''")
