"""Build: a visual spec becomes a valid NOOA Agent module."""

from __future__ import annotations

import ast
from pathlib import Path

from src.schemas import BuildSpec, FieldSpec, MethodSpec

STRATEGY_IMPORT = {
    "Predict": "PredictStrategy",
    "CodeAct": "CodeActStrategy",
}

_DEFAULTS = {"str": '""', "int": "0", "float": "0.0", "bool": "False"}


def generate_source(spec: BuildSpec) -> str:
    if not spec.methods:
        raise ValueError("add at least one method")
    agentic = [m for m in spec.methods if m.kind == "agentic"]
    strategies = sorted({STRATEGY_IMPORT[m.strategy] for m in agentic})
    role = _triple(spec.role.strip() or "You are a focused specialist agent.")
    chunks = [
        '"""Generated by ClassAct. Agent class for NVIDIA Object-Oriented Agents."""',
        "",
        "from nooa import Agent, strategy" if strategies else "from nooa import Agent",
    ]
    if strategies:
        chunks.append(f"from nooa.strategies import {', '.join(strategies)}")
    chunks += ["", "", f"class {spec.class_name}(Agent):", f'    """{role}"""', ""]
    if spec.fields:
        for field in spec.fields:
            chunks.append(_field_line(field))
        chunks.append("")
    for method in spec.methods:
        chunks.append(_method_block(method))
        chunks.append("")
    source = "\n".join(chunks).rstrip() + "\n"
    ast.parse(source)
    return source


def write_agent(spec: BuildSpec, workspace: Path) -> Path:
    source = generate_source(spec)
    workspace.mkdir(parents=True, exist_ok=True)
    path = workspace / f"{_mod_name(spec.class_name)}.py"
    path.write_text(source, encoding="utf-8")
    return path


def _mod_name(class_name: str) -> str:
    chars = []
    for i, ch in enumerate(class_name):
        if ch.isupper() and i and class_name[i - 1].islower():
            chars.append("_")
        chars.append(ch.lower())
    name = "".join(chars)
    if not name.endswith("_agent"):
        name = name + "_agent" if not name.endswith("agent") else name
    return name


def _field_line(field: FieldSpec) -> str:
    return f"    {field.name}: {field.type} = {_DEFAULTS[field.type]}"


def _method_block(method: MethodSpec) -> str:
    args = ", ".join(["self"] + [f"{a.name}: {a.type}" for a in method.args])
    doc = _triple(method.doc.strip() or f"Run {method.name}.")
    if method.kind == "python":
        ret = _DEFAULTS.get(method.returns, "None")
        return (
            f"    def {method.name}({args}) -> {method.returns}:\n"
            f'        """{doc}"""\n'
            f"        return {ret}"
        )
    strat = STRATEGY_IMPORT[method.strategy]
    return (
        f"    @strategy({strat}())\n"
        f"    async def {method.name}({args}) -> {method.returns}:\n"
        f'        """{doc}"""\n'
        f"        ..."
    )


def _triple(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"""', "'''")
